//*************************************/
/*Assignment 1 by Harsukh Singh
 * This program is designed to test the users typing speed.
 * The words are hard coded in as per the assignment design. The time is read a floating point value.
 * Version 1 4/10/2015
 ***************************************/
#include <sys/time.h> // used for timersub finction, gettimeofday and timeval structs
#include <stdio.h> //input and output library
#include <string.h> //used for strlen
#include <stdlib.h> //used for rand and seeding rand (srand)
//function definitions begin here
double get_time(char*, int count);
double permutation(char**);
int check_string(char*, char*);
//main function
/*@author harsukh singh
 *@function main hard codes the words to be typed and prints the total time and time as words per minute
 *@params void
 *@return exit as int 0
 */
int main()
{
    char* temp[9];
    temp[0] = "The";
    temp[1] = "quick";
    temp[2] = "brown";
    temp[3] = "fox";
    temp[4] = "jumped";
    temp[5] = "over";
    temp[6] = "the";
    temp[7] = "lazy";
    temp[8] = "dog";
    double time = permutation(temp);
    //float time_per_word = (time/9) *(60);
   // printf("your time is %f words per minute \n", time_per_word);
    printf("you total time is %f \n", time);
    return 0;
}
//program begins here
/* @author harsukh singh
 * @function gets user input time based on a string as a floating point value of time.
 * @params string as a char* and the word count as they are flushed to output buffer
 * @return float value of time of each word typed
 */
double get_time(char* temp, int count)
{
    char* to_read = malloc(80*4); //
    struct timeval beg;
    struct timeval end;
    struct timeval res;
    gettimeofday(&beg, NULL);
    printf("word is %d %s : ", count, temp);
    scanf("%79s", to_read);
    while(check_string(to_read, temp) != 1)
    {
        printf("word %d is %s : ", count, temp);
        scanf("%79s", to_read);
    }
    free(to_read);
    gettimeofday(&end, NULL);
    timersub(&end, &beg, &res);
    //printf("seconds are %lu", res.tv_sec);
    //printf("microseconds are %lu" ,res.tv_usec);
    return (double)(res.tv_sec + (res.tv_usec*1.0e-6));
}
/*
 * @author harsukh singh
 * @function generates a permutation of the words based on index generated by rand function
 * @params the pointer to the array of pointers which point to the strings
 * @return the floating point value of total time
 */
double permutation(char** temp)
{
    double scores[9];
    int j;
    int words = 0;
    for(j = 0; j<9;++j)
    {
        scores[j] = 0;
    }
    struct timeval start;
    gettimeofday(&start, NULL);
    srand(start.tv_sec);
    for(j = 9;j > 0; --j)
    {
        int index = rand() % j;
        if(temp[index] != NULL)
        {
            scores[index] = get_time(temp[index], ++words);
            temp[index] = NULL;
        }
    }
    int p;
    for(p = 0; p<9; ++p)
    {
        if(temp[p] != NULL)
        {
            scores[p] = get_time(temp[p], ++words);
            temp[p] = NULL;
        }
    }
    int i;
    double sum = 0.0;
    for(i = 0; i<9; ++i)
    {
        sum = scores[i] + sum;
    }
    return sum;

}
/*
 * @author harsukh singh
 * @function check string function takes a guess word and compares it against the check
 * @param a guess word and a word to check against
 * @return 1 or 0
 */
int check_string(char* guess, char* check) //compares the guess word to the known check word 
{
    char* comp1;
    char* comp2;
    int success = 0;
    int length = 0;
    char* temp_guess = (char*) malloc(((unsigned) strlen(guess) + 1));
    char* temp_check = (char*) malloc(((unsigned) strlen(check) + 1));
    unsigned int i;
    for(i = 0; i<(unsigned) strlen(guess); ++i)
    {
        if(guess[i] != ' ')
        {
            temp_guess[length] = guess[i];
            ++length;
        }
    }
    temp_guess[length] = '\0';
    length = 0;
    unsigned int j;
    for(j = 0; j<(unsigned) strlen(check); ++j){
        
        if(check[j] != ' ')
        {
            temp_check[length] = check[j];
            ++length;
        }
    }
    temp_check[length] = '\0';
    length = 0;
    unsigned int k;
    if((unsigned) strlen(temp_guess) != (unsigned) strlen(temp_check)) return success;
    if(temp_check[0] == temp_guess[0])
    { 
        int count = 0;
        comp1 = &temp_check[0];
        comp2 = &temp_guess[0];
        while(*comp1 == *comp2)
        {
            comp1 = comp1 +1;
            comp2 = comp2 +1;
            count = count + 1;
            if(count == ( unsigned) strlen(temp_check)){
                success = 1;
                free(temp_check);
                free(temp_guess);
                return success;
            } 
        } 
    }
    free(temp_check);
    free(temp_guess);
    return success;
}
